steps:

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'asia-southeast2-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/hello-world:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'asia-southeast2-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/hello-world:$SHORT_SHA']

  - name: google/cloud-sdk
    args: ['gcloud', 'run', 'deploy', 'hello-world-python', 
           '--image=us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/hello-world:$SHORT_SHA', 
           '--region', 'asia-southeast2', '--platform', 'managed', 
           '--allow-unauthenticated']

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/hello-world-python:$SHORT_SHA

